# Generated by Django 5.0.6 on 2024-06-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patataj', '0003_alter_trainingplan_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
