# Generated by Django 5.0.6 on 2024-06-10 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('training_type', models.CharField(choices=[('SK', 'Skokowy'), ('UJ', 'Ujeżdżeniowy'), ('LO', 'Lonża'), ('PZ', 'Praca z ziemi'), ('TE', 'Teren'), ('CR', 'Cross')], max_length=2)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SK', 'Skokowy'), ('UJ', 'Ujeżdżeniowy'), ('LO', 'Lonża'), ('PZ', 'Praca z ziemi'), ('TE', 'Teren'), ('CR', 'Cross')], max_length=2)),
                ('description', models.TextField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('PN', 'Poniedziałek'), ('WT', 'Wtorek'), ('SR', 'Środa'), ('CZ', 'Czwartek'), ('PT', 'Piątek'), ('SB', 'Sobota'), ('ND', 'Niedziela')], default='PN', max_length=2)),
                ('time', models.TimeField()),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingplans.horse')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingplans.plan')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingplans.trainer')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingplans.training')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='trainings',
            field=models.ManyToManyField(through='trainingplans.TrainingPlan', to='trainingplans.training'),
        ),
    ]
