# Generated by Django 5.0.6 on 2024-06-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingplans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='name',
        ),
    ]
